version: '3'
services:
  bdfr-html:                                #Container which runs both bdfr and bdfr-html
    container_name: bdfr-html
    build: .                                #Builds from current folder, could also build from git repo
    environment:                            
      - BDFRH_LOGLEVEL=INFO                 #Either INFO or DEBUG for more verbose logs
    volumes:
      - output:/bdfrh/output                      #Shared docker volume between the script container and the webserver, could also be mounted
      - ./config:/root/.config/bdfr/        #Mounted folder where the bdfr config file lives
      #- ./cfg/:/bdfrh/config               #If you'd like to mount the cfg file for bdfrhtml
    ports:
      - "7634:7634"
  apache:                                   #Standard webserver serving the content located in the BDFR_OUT var
    image: httpd:alpine
    container_name: bdfr-server
    ports:
      - "80:80"                             #Ports can be redefined as needed
    volumes:
      - output:/usr/local/apache2/htdocs/   #This should match the output volume or mount in the script container

volumes:
  output: